verbosity = 2

[server]
# exit session if no requests were received during given period in seconds
# # works only in unix sockets mode (-s/--session)
# # set to 0 to disable
timeout = 1800 # seconds = 30 minutes

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"

[language.javascript]
filetypes = ["javascript"]
roots = ["package.json"]
command = "javascript-typescript-stdio"
args = []

[language.json]
filetypes = ["json"]
roots = ["package.json"]
command = "json-languageserver"
args = ["--stdio"]

[language.css]
filetypes = ["css"]
roots = ["package.json"]
command = "css-languageserver"
args = ["--stdio"]

[language.html]
filetypes = ["html"]
roots = ["package.json"]
command = "html-languageserver"
args = ["--stdio"]

